/* tslint:disable */
 
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Book {
  description?: string | null;
  excerpt?: string | null;
  id?: number;
  pageCount?: number;
  publishDate?: string;
  title?: string | null;
}
